export const AudioMap: Record<string, any> = {
    "2025_03__Clement_Panchout__Music_Weeklies_25_DM__16_Bit_GEN_Death_metalwav": require("../../../assets/music/combat/2025 03 _ Clement Panchout - Music Weeklies 25 DM - 16 Bit GEN Death metalwav.wav"),
    "Clement_Panchout_Kick_Me_Harder_2001": require("../../../assets/music/combat/Clement Panchout_ Kick Me Harder_ 2001.wav"),
    "Space_Horror_Boss_Music_Clement_Panchout": require("../../../assets/music/combat/Space Horror Boss Music _Clement Panchout.wav"),
    "Clement_Panchout__Revenge": require("../../../assets/music/combat/Clement Panchout _ Revenge.wav"),
    "Clement_Panchout__Unsettling_victory__2019": require("../../../assets/music/combat/Clement Panchout _ Unsettling victory _ 2019.wav"),
    "Clement_Panchout__Violence": require("../../../assets/music/combat/Clement Panchout _ Violence.wav"),
    "Clement_Panchout__Round_Glasses__2016": require("../../../assets/music/exploration/Clement Panchout _ Round Glasses _ 2016.wav"),
    "Clement_Panchout__Dark__2004": require("../../../assets/music/exploration/Clement Panchout _ Dark _ 2004.wav"),
    "Clement_Panchout_Feat_Katcho_Desert_2002": require("../../../assets/music/exploration/Clement Panchout (Feat Katcho)_ Desert_ 2002.wav"),
    "Clement_Panchout_feat_Katcho_Gothic_Picture_2002": require("../../../assets/music/exploration/Clement Panchout (feat Katcho)_ Gothic Picture_ 2002.wav"),
    "Time_Flies_Clement_Panchout_2016": require("../../../assets/music/exploration/Time Flies _Clement Panchout _2016.wav"),
    "Space_Horror_Boss_Music_Clement_Panchout": require("../../../assets/music/exploration/Space Horror Boss Music _Clement Panchout.wav"),
    "Space_Horror_InGame_Music_Exploration_Clement_Panchout": require("../../../assets/music/exploration/Space Horror InGame Music (Exploration) _Clement Panchout.wav"),
    "Clement_Panchout_Forest_Of_A_Thousand_Masks": require("../../../assets/music/exploration/Clement Panchout_ Forest Of A Thousand Masks.wav"),
    "Retro_Spooky_Soundscape_The_Whispering_Shadows_Dungeon_Clement_Panchout_2016": require("../../../assets/music/exploration/Retro_ Spooky Soundscape_ The Whispering Shadows Dungeon _Clement Panchout 2016.wav"),
    "Clement_Panchout__I_want_to_believe__2004": require("../../../assets/music/exploration/Clement Panchout _ I want to believe _ 2004.wav"),
    "Clement_Panchout_Village_2002": require("../../../assets/music/exploration/Clement Panchout_ Village_ 2002.wav"),
    "Modern__Eastern__Arabian_Princess__Clement_Panchout_2019": require("../../../assets/music/exploration/Modern _ Eastern _ Arabian Princess _ Clement Panchout 2019.wav"),
    "2019_09_Clement_Panchout_Shadowl_OST_Shadowl": require("../../../assets/music/exploration/2019 09_ Clement Panchout_ Shadowl OST_ Shadowl.wav"),
    "Clement_Panchout__Journey__2017": require("../../../assets/music/exploration/Clement Panchout _ Journey _ 2017.wav"),
    "Space_Horror_InGame_Music_Tense_Clement_Panchout": require("../../../assets/music/exploration/Space Horror InGame Music (Tense) _Clement Panchout.wav"),
};
